# Generated by Django 5.0.4 on 2024-12-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Santa_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment', models.CharField(default='Coal for bad behavior', max_length=100)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Santa_list.kid')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_type', models.CharField(max_length=100)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Santa_list.kid')),
            ],
        ),
    ]
