# Generated by Django 5.0.4 on 2024-12-26 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('niceness_coefficient', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('gift', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SantaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santa_lists', to='Santa_list.kid')),
                ('naughty_list', models.ManyToManyField(blank=True, related_name='naughty_lists', to='Santa_list.kid')),
                ('nice_list', models.ManyToManyField(blank=True, related_name='nice_lists', to='Santa_list.kid')),
            ],
        ),
    ]
